language: bash

os:
  - linux
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install r-base-core; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install r; fi

before_script:
  - sudo R -e 'install.packages(c("devtools"), repos="http://cran.us.r-project.org")'

script:
  - echo 123
